CREATE TABLE SALE(OrderID VARCHAR(50),
OrderDate DATE,
Region VARCHAR(50),
Category VARCHAR(50),
Segment VARCHAR(50),
Quantity NUMERIC,
UnitCost NUMERIC,
UnitPrice NUMERIC,
Sales NUMERIC,
Cost NUMERIC,
Profit NUMERIC,
Year NUMERIC,
Month VARCHAR(50)
);


--use extract (month from order date)

SELECT
EXTRACT(MONTH FROM ORDERDATE) AS ORDER_MONTH,
SUM(SALES) AS SALES
FROM SALE
GROUP BY EXTRACT(MONTH FROM ORDERDATE)
ORDER BY ORDER_MONTH


--group by year/month


SELECT EXTRACT(YEAR FROM ORDERDATE) AS ORDER_YEAR,
EXTRACT(MONTH FROM ORDERDATE) AS ORDER_MONTH,
SUM(SALES) AS SALES
FROM SALE
GROUP BY EXTRACT(YEAR FROM ORDERDATE),
EXTRACT(MONTH FROM ORDERDATE)
ORDER BY ORDER_YEAR,ORDER_MONTH


--use sum for revenue

SELECT SUM(PROFIT) AS REVENUE
FROM SALE



--count (orderid)

SELECT COUNT(ORDERID) AS TOTAL_ID
FROM SALE


--use order by for shoting top 5


SELECT SEGMENT, SUM(SALES) AS SALES
FROM SALE
GROUP BY SEGMENT,SALES
ORDER BY SALES DESC


--limit result for specific time periods

SELECT CATEGORY, SUM(SALES) AS SALES
FROM SALE
GROUP BY CATEGORY,SALES
ORDER BY SALES DESC
LIMIT 5


select * from sale